package edrRecon

//Edrlist is a list of edrs.
var EdrList = []string{
	"activeconsole",
	"amsi.dll",
	"anti malware",
	"anti-malware",
	"antimalware",
	"anti virus",
	"anti-virus",
	"antivirus",
	"appsense",
	"authtap",
	"avast",
	"avecto",
	"canary",
	"carbonblack",
	"carbon black",
	"cb.exe",
	"ciscoamp",
	"cisco amp",
	"countercept",
	"countertack",
	"cramtray",
	"crssvc",
	"crowdstrike",
	"csagent",
	"csfalcon",
	"csshell",
	"cybereason",
	"cyclorama",
	"cylance",
	"cyoptics",
	"cyupdate",
	"cyvera",
	"cyserver",
	"cytray",
	"darktrace",
	"defendpoint",
	"defender",
	"eectrl",
	"elastic",
	"endgame",
	"f-secure",
	"forcepoint",
	"fireeye",
	"groundling",
	"GRRservic",
	"inspector",
	"ivanti",
	"kaspersky",
	"lacuna",
	"logrhythm",
	"malware",
	"mandiant",
	"mcafee",
	"morphisec",
	"msascuil",
	"msmpeng",
	"nissrv",
	"omni",
	"omniagent",
	"osquery",
	"Palo Alto Networks",
	"pgeposervice",
	"pgsystemtray",
	"privilegeguard",
	"procwall",
	"protectorservic",
	"qradar",
	"redcloak",
	"secureworks",
	"securityhealthservice",
	"semlaunchsv",
	"sentinel",
	"sepliveupdat",
	"sisidsservice",
	"sisipsservice",
	"sisipsutil",
	"smc.exe",
	"smcgui",
	"snac64",
	"sophos",
	"splunk",
	"srtsp",
	"symantec",
	"symcorpu",
	"symefasi",
	"sysinternal",
	"sysmon",
	"tanium",
	"tda.exe",
	"tdawork",
	"tpython",
	"vectra",
	"wincollect",
	"windowssensor",
	"wireshark",
	"threat",
	"xagt.exe",
	"xagtnotif.exe",
}

var ReconList = []string{
	"ProductName",
	"CSDVersion",
	"CurrentVersion",
	"CurrentBuild",
	"SystemRoot",
	"RegisteredOrganization",
	"Domain",
	"DhcpNameServer",
	"DhcpDomain",
	"SystemManufacturer",
	"SystemProductName",
	"LocalAccountTokenFilterPolicy",
	"LsaCfgFlags",
}

var McafeeList = []string{
	"Mcafee\\",
	"McAfeeAgent\\",
	"APPolicyName",
	"EPPolicyName",
	"OASPolicyName",
}

var SymantecList = []string{
	"Symantec",
	"Symantec Endpoint Protection\\",
}

var WinDefender = []string{
	"Windows Defender",
	"DpaDisabled",
	"DisableRealTimeMonitoring",
}

var WinDefenderATP = []string{}

var CarbonBlack = []string{
	"CarbonBlack\\",
	"CbDefense\\",
	"SensorVersion",
}

var CrowdStrike = []string{
	"CrowdStrike\\",
	"%SYSTEMROOT%\\system32\\drivers\\crowdstrike\\CsDeviceControl.inf",
	"%SYSTEMROOT%\\system32\\drivers\\crowdstrike\\CsFirmwareAnalysis.inf",
}

var Cylance = []string{
	"Cylance\\",
	"Cylance0",
	"Cylance1",
	"Cylance2",
}

var FireEye = []string{
	"FireEye",
}

var SentinelOne = []string{
	"Sentinel Labs\\",
	"Sentinel Agent\\",
	"externalID",
}

var RegistryReconList = []string{
	"Sentinel Labs\\",
	"Sentinel Agent\\",
	"externalID",
	"FireEye",
	"Cylance\\",
	"Cylance0",
	"Cylance1",
	"Cylance2",
	"CrowdStrike\\",
	"%SYSTEMROOT%\\system32\\drivers\\crowdstrike\\CsDeviceControl.inf",
	"%SYSTEMROOT%\\system32\\drivers\\crowdstrike\\CsFirmwareAnalysis.inf",
	"Mcafee\\",
	"McAfeeAgent\\",
	"APPolicyName",
	"EPPolicyName",
	"OASPolicyName",
	"Symantec",
	"Symantec Endpoint Protection\\",
	"Windows Defender",
	"DpaDisabled",
	"DisableRealTimeMonitoring",
	"CarbonBlack\\",
	"CbDefense\\",
	"SensorVersion",
}
